// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, name, description, price, quantity, created_at, updated_at)
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3,
  $4,
  NOW(),
  NOW()
)
RETURNING id, name, description, price, quantity, created_at, updated_at
`

type CreateItemParams struct {
	Name        string
	Description string
	Price       int32
	Quantity    int32
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItemByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItemByID, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, description, price, quantity, created_at, updated_at FROM items
ORDER BY name
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name, description, price, quantity, created_at, updated_at FROM items
WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAndItem = `-- name: GetUserAndItem :one
SELECT users.balance, items.price, items.quantity
FROM users
JOIN items ON items.id = $2
WHERE users.id = $1
`

type GetUserAndItemParams struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

type GetUserAndItemRow struct {
	Balance  int32
	Price    int32
	Quantity int32
}

func (q *Queries) GetUserAndItem(ctx context.Context, arg GetUserAndItemParams) (GetUserAndItemRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAndItem, arg.ID, arg.ID_2)
	var i GetUserAndItemRow
	err := row.Scan(&i.Balance, &i.Price, &i.Quantity)
	return i, err
}

const updateQuantity = `-- name: UpdateQuantity :one
UPDATE items
SET quantity = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, name, description, price, quantity, created_at, updated_at
`

type UpdateQuantityParams struct {
	Quantity int32
	ID       uuid.UUID
}

func (q *Queries) UpdateQuantity(ctx context.Context, arg UpdateQuantityParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateQuantity, arg.Quantity, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
