// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       int32
	Quantity    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID             uuid.UUID
	Name           string
	Balance        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	IsAdmin        bool
}
