// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, balance)
VALUES (
  gen_random_uuid(),
  $1,
  $2
  )
RETURNING id, name, balance
`

type CreateUserParams struct {
	Name    string
	Balance int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Balance)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Balance)
	return i, err
}
